export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";
